version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version  # Check Maven version to ensure it's installed
      - echo Installing dependencies...
      - mvn install -DskipTests  # Install dependencies, skipping tests
  pre_build:
    commands:
      - echo Running pre-build scripts...
      - mvn clean  # Clean previous builds
  build:
    commands:
      - echo Building the project...
      - mvn compile  # Compile the source code
      - mvn package  # Package the code into a JAR/WAR file
  post_build:
    commands:
      - echo Build complete.
      - echo Running tests...
      - mvn test  # Run tests
      - echo Build artifacts generated: target/*.jar

artifacts:
  files:
    - target/*.jar  # Specify the path to your built JAR/WAR files
  discard-paths: yes

cache:
  paths:
    - '~/.m2/**/*'  # Cache Maven dependencies to speed up subsequent builds
